<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sathvik" ignored="0" name="Test" tests="4" failures="1" timestamp="27 Sep 2018 11:27:49 GMT" time="68.342" errors="0">
  <testcase name="launch" time="8.586" classname="Way2SMSModule.LoginPageTesting"/>
  <testcase name="login" time="3.941" classname="Way2SMSModule.LoginPageTesting"/>
  <testcase name="sendMessage" time="54.775" classname="Way2SMSModule.SendSMSTest">
    <failure type="java.lang.AssertionError" message="Way2SMS Login Test was Interrupted expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Way2SMS Login Test was Interrupted expected [true] but found [false]
at Way2SMSModule.SendSMSTest.sendMessage(SendSMSTest.java:59)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- sendMessage -->
  <testcase name="close" time="1.013" classname="Way2SMSModule.LoginPageTesting"/>
</testsuite> <!-- Test -->
